#![no_std]
#![doc = include_str!("../CATALOG.md")]
//! Adversarial Soroban contract mocks for negative-path testing at every
//! cross-contract trust boundary in the Zenith protocol.
//!
//! ## Usage
//!
//! Add `zenith-test-adversaries` as a dev-dependency, then register any
//! adversary in a test `Env` the same way you'd register a real contract:
//!
//! ```rust,ignore
//! use test_adversaries::tokens::LyingBalanceToken;
//! let bad_token = env.register_contract(None, LyingBalanceToken);
//! ```
//!
//! Every adversary is a standalone `#[contract]` that mirrors the interface
//! of the real contract it spoofs. Clients generated by the real crates'
//! `contractimport!` / testutils work against them transparently.
//!
//! See the adversary catalog in `CATALOG.md` for the full list and the
//! specific vulnerability each adversary exercises.

pub mod multisig;
pub mod oracle;
pub mod tokens;
pub mod vault;
